### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by beeprime** [righettod/owasp-cs-book#3]
After fetching all the CS it crashes while merging into a single pdf

FileNotFoundError: [Errno 2] No such file or directory: '/home/git-repo/owasp-cs-book/work/65aeac03929cc575db9f9410a801c1cb.pdf'

**Comment by righettod** [comment]
Do you run the generation on a Linux server without UI ?

If yes then check this [script](https://github.com/righettod/owasp-cs-book/blob/master/setup-for-exec-no-x-server.sh) to fix the problem.
